spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/libro
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres